### ISSUE TITLE
Multiple madlibs that the user could see

### ISSUE THREAD

**Issue by mt-digital** [mtpain/Madlibs.Today#5]
Write or find 5 madlibs to show the user. Put these in JSON format, saved to the filesystem with a `.json` extension. Include these in the repository the `static/madlibs` directory. When the client requests `/madlib-today`, they will see one of the five madlibs.

**Comment by dannyzamora** [comment]
Is this portion that Amy and I have to do?

**Comment by mt-digital** [comment]
@dannyzamora yes
